"""GitHub Pull Request creator.

Creates PRs for validated fixes via GitHub API.
"""
import logging
from typing import Any

import httpx

from sre_agent.config import get_settings
from sre_agent.schemas.pr import PRRequest, PRResult, PRStatus

logger = logging.getLogger(__name__)


PR_BODY_TEMPLATE = """## 🤖 Auto-Generated Fix

This PR was automatically generated by the SRE Agent to fix a CI/CD failure.

### Root Cause Analysis
- **Category**: {category}
- **Confidence**: {confidence:.0%}
- **Hypothesis**: {hypothesis}

### Affected Files
{affected_files}

### Validation Results
- ✅ Tests Passed: {tests_passed}
- ❌ Tests Failed: {tests_failed}
- 📊 Status: {validation_status}

### Changes
<details>
<summary>View diff</summary>

```diff
{diff_preview}
```

</details>

### Original Failure
- Event ID: `{event_id}`
- Fix ID: `{fix_id}`

---
*Generated by [SRE Agent](https://github.com/org/sre-agent) | [Learn more](https://docs.example.com/sre-agent)*
"""


class PRCreator:
    """
    Creates GitHub Pull Requests for validated fixes.

    Uses GitHub REST API to:
    - Create pull requests
    - Add labels
    - Link to issues
    """

    def __init__(
        self,
        token: str | None = None,
        base_url: str = "https://api.github.com",
    ):
        """
        Initialize PR creator.

        Args:
            token: GitHub personal access token
            base_url: GitHub API base URL
        """
        settings = get_settings()
        self.token = token or settings.github_token
        self.base_url = base_url.rstrip("/")

        if not self.token:
            logger.warning("GitHub token not configured - PR creation will fail")

    def _build_headers(self) -> dict[str, str]:
        """Build request headers."""
        return {
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {self.token}",
            "X-GitHub-Api-Version": "2022-11-28",
        }

    async def create_pr(
        self,
        request: PRRequest,
        branch_name: str,
    ) -> PRResult:
        """
        Create a GitHub Pull Request.

        Args:
            request: PR creation request
            branch_name: Source branch with fix

        Returns:
            PRResult with PR URL and status
        """
        logger.info(
            "Creating PR",
            extra={
                "repo": request.repo,
                "branch": branch_name,
                "fix_id": request.fix_id,
            },
        )

        # Generate title
        title = request.title or self._generate_title(request)

        # Generate body
        body = request.description or self._generate_body(request)

        try:
            async with httpx.AsyncClient(
                base_url=self.base_url,
                headers=self._build_headers(),
                timeout=30.0,
            ) as client:
                # Create PR
                response = await client.post(
                    f"/repos/{request.repo}/pulls",
                    json={
                        "title": title,
                        "body": body,
                        "head": branch_name,
                        "base": request.base_branch,
                    },
                )

                if response.status_code == 201:
                    data = response.json()
                    pr_number = data["number"]
                    pr_url = data["html_url"]

                    # Add labels
                    await self._add_labels(
                        client,
                        request.repo,
                        pr_number,
                    )

                    logger.info(
                        "PR created successfully",
                        extra={"pr_number": pr_number, "pr_url": pr_url},
                    )

                    return PRResult(
                        pr_number=pr_number,
                        pr_url=pr_url,
                        status=PRStatus.CREATED,
                        branch_name=branch_name,
                        base_branch=request.base_branch,
                        fix_id=request.fix_id,
                        event_id=request.event_id,
                        title=title,
                    )
                else:
                    error_msg = response.text
                    logger.error(f"Failed to create PR: {error_msg}")

                    return PRResult(
                        status=PRStatus.FAILED,
                        branch_name=branch_name,
                        base_branch=request.base_branch,
                        fix_id=request.fix_id,
                        event_id=request.event_id,
                        error_message=error_msg,
                    )

        except Exception as e:
            logger.error(f"Error creating PR: {e}", exc_info=True)

            return PRResult(
                status=PRStatus.FAILED,
                branch_name=branch_name,
                base_branch=request.base_branch,
                fix_id=request.fix_id,
                event_id=request.event_id,
                error_message=str(e),
            )

    async def _add_labels(
        self,
        client: httpx.AsyncClient,
        repo: str,
        pr_number: int,
        labels: list[str] | None = None,
    ) -> None:
        """Add labels to a PR."""
        labels = labels or ["auto-fix", "sre-agent"]

        try:
            await client.post(
                f"/repos/{repo}/issues/{pr_number}/labels",
                json={"labels": labels},
            )
        except Exception as e:
            logger.warning(f"Failed to add labels: {e}")

    def _generate_title(self, request: PRRequest) -> str:
        """Generate PR title."""
        if request.error_type:
            files = request.affected_files[:2]
            file_str = ", ".join(f.split("/")[-1] for f in files)
            return f"fix: {request.error_type} in {file_str} [auto-generated]"

        return f"fix: CI failure fix [auto-generated] ({request.fix_id[:8]})"

    def _generate_body(self, request: PRRequest) -> str:
        """Generate PR body from template."""
        affected = "\n".join(f"- `{f}`" for f in request.affected_files[:10])
        if not affected:
            affected = "- No specific files identified"

        # Truncate diff preview
        diff_preview = request.diff[:2000]
        if len(request.diff) > 2000:
            diff_preview += "\n... (truncated)"

        return PR_BODY_TEMPLATE.format(
            category=request.error_type or "Unknown",
            confidence=request.confidence or 0,
            hypothesis=request.hypothesis or "Fix generated based on error analysis",
            affected_files=affected,
            tests_passed=request.tests_passed,
            tests_failed=request.tests_failed,
            validation_status=request.validation_status or "Not validated",
            diff_preview=diff_preview,
            event_id=str(request.event_id),
            fix_id=request.fix_id,
        )

    async def close_pr(
        self,
        repo: str,
        pr_number: int,
        comment: str | None = None,
    ) -> bool:
        """
        Close a PR.

        Args:
            repo: Repository
            pr_number: PR number
            comment: Optional closing comment

        Returns:
            True if successful
        """
        async with httpx.AsyncClient(
            base_url=self.base_url,
            headers=self._build_headers(),
            timeout=30.0,
        ) as client:
            if comment:
                await client.post(
                    f"/repos/{repo}/issues/{pr_number}/comments",
                    json={"body": comment},
                )

            response = await client.patch(
                f"/repos/{repo}/pulls/{pr_number}",
                json={"state": "closed"},
            )

            return response.status_code == 200
